### PR TITLE
add support for github app auth

### PR DESCRIPTION
**Pull request by DrFaust92**
Closes https://github.com/zapier/kubechecks/issues/247

### CODE REVIEW

**Comment by djeebus** [comment]
Looks good to me! I'll run some tests locally, but (assuming all looks good) we'll get this merged. Thanks!

**Comment by DrFaust92** [comment]
[djeebus](https://github.com/djeebus) any news?

**Comment by djeebus** [comment]
News! Sorry about the delay. Had to make some changes to get it to work, but #288 should have it implemented. If you get a chance, mind testing it out, see if it works for you?

**Comment by djeebus** [comment]
Closing in order to focus on #288

**Pull request closed without merging**
