### PR TITLE
fix: Set `success` Git commit status in case of skipped checks

### PR DESCRIPTION
**Pull request by andridzi**

### CODE REVIEW

**Comment by djeebus** [comment]
Good catch, thanks! Mind taking a shot at implementing it for gitlab as well?

**Comment by andridzi** [comment]
sure, done
gitlab part completely went out of my head

**Comment by andridzi** [comment]
hello @djeebus 
what is your release/merge strategy, any chance this one can be processed?

**Review by djeebus — APPROVED** [review]

**Comment by djeebus** [comment]
> hello @djeebus what is your release/merge strategy, any chance this one can be processed?

"Strategy" is a strong word, mostly we release when someone pokes us. Release coming!

**Comment by djeebus** [comment]
[v1.8.1](https://github.com/zapier/kubechecks/releases/tag/v1.8.1), thanks!

**Pull request merged**
