### PR TITLE
Add initContainers support

### PR DESCRIPTION
**Pull request by shlomitubul**
Currently, there is no option to configure Kubecheck to authenticate against OCI registries like GCR/GAR. By adding support for initContainers, users can set up credential helpers such as docker-credential-gcr to generate a config.json for Docker authentication, the initContainer  can also copies the docker-credential-gcr binary into the main Kubecheck container, allowing it to successfully fetch tokens and authenticate

### CODE REVIEW

**Comment by shlomitubul** [comment]
example in GCP GAR:
```
 rest of yaml omited...
 volumes:
  - name: registry-config
    emptyDir: {}
  - name: cred-helper
    emptyDir: {} 
  volumeMounts:
  - name: registry-config
    mountPath: /root/.docker
  - name: cred-helper
    mountPath: /usr/bin/docker-credential-gcr
    subPath: docker-credential-gcr
  initContainers:
  - name: gcp-cred-helper
    image: google/cloud-sdk:472.0.0-slim
    command: ["/bin/sh", "-c"]
    args:
      - |
        curl -fsSL "https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v2.1.25/docker-credential-gcr_linux_amd64-2.1.25.tar.gz" |
        tar xz docker-credential-gcr &&
        chmod +x docker-credential-gcr &&
        cp docker-credential-gcr /usr/bin/ &&
        mv docker-credential-gcr /shared/ &&
        docker-credential-gcr configure-docker --registries=us-central1-docker.pkg.dev
    volumeMounts:
      - name: registry-config
        mountPath: /root/.docker
      - name: cred-helper
        mountPath: /shared
serviceAccount:
  create: true
  enabled: true
  name: kubechecks
  annotations:
    iam.gke.io/gcp-service-account: kubechecks@my-project.iam.gserviceaccount.com
```

**Comment by orenlevi111** [comment]
I Assume its working for u,
Altough it won't work with temp credentials like Aws Ecr provides.

**Comment by orenlevi111** [comment]
Since the creds expire after 12 hours.
And u mount it just once in the initcontainer.

**Comment by shlomitubul** [comment]
> Since the creds expire after 12 hours. And u mount it just once in the init container.

I don't mount static creds, I only instruct helm to use cred helper, then each time kubecheck run, then `helm dependency build` get invoked (technically by good lib not kubecheck itself) and in turn he run docker-credential to get fresh token

**Comment by shlomitubul** [comment]
> This looks quite reasonable, and likely is useful for other reasons as well (network sidecars, secret providers, etc). You might also try out the image from the [multisource apps PR](#298), as that shifts responsibility for manifest generation back to argocd's repo server. It might resolve your issue in more straightforward way (as I would imagine argocd has already been configured correctly).
> 
> Be aware that this also requires direct access to the backend repo service, generally located in the `argocd` namespace, called `argocd-repo-server`, on port 8081. If it's not configured that way, you can override it via `KUBECHECKS_ARGOCD_REPOSITORY_ENDPOINT`. I'd be interested in knowing your results, as this could provide more evidence that the extra complexity is worth the effort. Thanks!
> 
> image: ghcr.io/zapier/kubechecks:0.0.0-pr298

@djeebus, I reviewed the multi-source PR, and aside from all re-factoring, now we call then new `GetManifests` instead of `GetManifestsLocal` that sends tarball to the argo repo server for diff check?

**Comment by shlomitubul** [comment]
@djeebus can we merge this please ? we really like to start using this great tool ( :

**Review by noamgloberman0 — APPROVED** [review]

**Review by yonigolob1 — APPROVED** [review]

**Review by djeebus — APPROVED** [review]

**Pull request merged**
